variables:
    IP: "192.168.100.87:5000"
    image: "wisdomtest"
    tag: "0.1"

stages:
    - build
    - test

build:
    stage: build
    tags:
        - ant-runner
    script: 
        - echo 'Building...'
        - docker build -t $IP/$image:$tag .
        - docker tag $IP/$image:$tag $IP/$image:latest
        - docker push $IP/$image:$tag
        - docker push $IP/$image:latest

test:
    stage: test
    tags:
        - ant-runner
    script: 
        - echo 'Testing'
        - docker info
