#services:
 #   - frekele/ant:latest
    
stages:
    - build
    - test

build:
    stage: build
  #  image: frekele/ant:latest
    tags:
        - ant-runner
    script: 
        - echo 'Building...'
 #       - docker info
        - docker build -t test1.latest .

test:
    stage: test
    tags:
        - ant-runner
    script: 
        - echo 'Testing'
        - docker info
