stages:
    - build
    - test

test:
    stage: test
    tags:
        - ant-runner
    script: 
        - echo 'testing'

build:
    stage: build
    tags:
        - ant-runner
    script: 
        - echo 'Building...'
        - docker info
