stages:
    - build
    - test

build:
    stage: build
    tags:
        - ant-runner
    script: 
        - echo 'Building...'
        - docker build -t 192.168.100.87:5000/test:0.1 .
        - docker tag 192.168.100.87:5000/test:0.1 192.168.100.87:5000/test:latest
        - docker push 192.168.100.87:5000/test:latest

test:
    stage: test
    tags:
        - ant-runner
    script: 
        - echo 'Testing...'
        - docker info