image: openjdk:8

before_script:
  - apt-get update
  - apt-get -y install ant

stages:
  - build
  - test

ci_build:
  stage: build
  tags:
    - test runner
  script:
    - ant clean
    - ant package

ci_test:
  stage: test
  tags:
    - test runner
  script:
    - ant clean package TestHelloWorld
