#services:
 #   - frekele/ant:latest
    
stages:
    - build
    - test

build:
    stage: build
  #  image: frekele/ant:latest
    tags:
        - ant-runner
    script: 
        - echo 'Building...'
 #       - docker info
        - docker build -t test1:latest .
        - docker tag test1:latest 192.168.100.87:5000/buildimage:latest
        - docker push 192.168.100.87:5000/buildimage:latest

test:
    stage: test
    tags:
        - ant-runner
    script: 
        - echo 'Testing'
        - docker info