stages:
    - build
    - test

build:
    stage: build
    tags:
        - ant-runner
    script: 
        - echo 'Building...'
        - docker info

test:
    stage: test
    tags:
        - ant-runner
    script: 
        - echo 'Testing'
